export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS'
export const CART_ADD_FAIL = 'CART_ADD_FAIL'
export const CART_ADD_RESET = 'CART_ADD_RESET'

export const CART_REMOVE = 'CART_REMOVE'

export const CART_TRASH = 'CART_TRASH'

export const CART_SAVE_SHIPPING_INFO = 'CART_SAVE_SHIPPING_INFO'

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

export const CART_RESET = 'CART_RESET'
