export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_SHIP_REQUEST = 'ORDER_SHIP_REQUEST'
export const ORDER_SHIP_SUCCESS = 'ORDER_SHIP_SUCCESS'
export const ORDER_SHIP_FAIL = 'ORDER_SHIP_FAIL'
export const ORDER_SHIP_RESET = 'ORDER_SHIP_RESET'

export const ORDER_USER_REQUEST = 'ORDER_USER_REQUEST'
export const ORDER_USER_SUCCESS = 'ORDER_USER_SUCCESS'
export const ORDER_USER_FAIL = 'ORDER_USER_FAIL'
export const ORDER_USER_RESET = 'ORDER_USER_RESET'

export const ORDERS_LIST_REQUEST = 'ORDERS_LIST_REQUEST'
export const ORDERS_LIST_SUCCESS = 'ORDERS_LIST_SUCCESS'
export const ORDERS_LIST_FAIL = 'ORDERS_LIST_FAIL'
export const ORDERS_LIST_RESET = 'ORDERS_LIST_RESET'