export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'
export const PRODUCTS_LIST_RESET = 'PRODUCTS_LIST_RESET'

export const PRODUCTS_IDS_LIST_REQUEST = 'PRODUCTS_IDS_LIST_REQUEST'
export const PRODUCTS_IDS_LIST_SUCCESS = 'PRODUCTS_IDS_LIST_SUCCESS'
export const PRODUCTS_IDS_LIST_FAIL = 'PRODUCTS_IDS_LIST_FAIL'
export const PRODUCTS_IDS_LIST_RESET = 'PRODUCTS_IDS_LIST_RESET'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL' 